### ISSUE TITLE
`root` setting, passing an array with more than 1 elements

### ISSUE THREAD

**Issue by jerrygreen** [ReadyTalk/todolint#3]
I see you've added an ability to pass an array (from this issue https://github.com/ReadyTalk/todolint/issues/2; that's cool you've added it), but there's a strange thing happening when I pass an array with more than 1 elements. Look into this two cases:

## One element in array

My config:

```json
{
  "root": ["pages"],
  "tags": [
    {
      "label": "✓ TODO",
      "name": "TODO",
      "regex": "TODO: ",
      "style": ["cyan"]
    }
  ],
  "warn": {
    "fail": true,
    "message": "You have TODOs!",
    "tags": ["TODO"]
  }
}
```

Output:

```sh
$ todolint
pages/data_inbox.tsx
[Line 50]  ✓ TODO:return data 

You have TODOs!
error Command failed with exit code 1.
```

That's completely ok. But I wanna use several items in array (wanna lint several folders).

## Two elements in array

My config:

```json
{
  "root": ["pages", "src"],
  "tags": [
    {
      "label": "✓ TODO",
      "name": "TODO",
      "regex": "TODO: ",
      "style": ["cyan"]
    }
  ],
  "warn": {
    "fail": true,
    "message": "You have TODOs!",
    "tags": ["TODO"]
  }
}
```

Output:

```sh
$ todolint
pages/data_inbox.tsx
[Line 50]  ✓ TODO:return data 
✨  Done in 0.26s.
```

It prints the TODOs but it does not fail if the array (`root`) has more than 1 element

**Comment by jahndis** [comment]
This should be fixed now (1.0.5). Sorry about that. Let me know if it's still not behaving properly.
