### ISSUE TITLE
File links to direct into exact place in code

### ISSUE THREAD

**Issue by jerrygreen** [ReadyTalk/todolint#4]
It's possible to direct user to the exact place in code. For example, that's how TypeScript compiler does:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/13215662/72143271-3d14e500-33b8-11ea-99f4-c78fa008e37e.png">

These links open exact row and column in code. While `todolint` (great little tool btw!) only opens just file, not exact place, because links don't have this info:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/13215662/72143406-7f3e2680-33b8-11ea-8787-ae5d0fa778e0.png">

Changes required for this should be somewhere here:

https://github.com/ReadyTalk/todolint/blob/6f6078487c35313271f3b15054054f4199f65cb1/todolint.js#L114-L121

**Comment by jahndis** [comment]
Hey I like the suggestion. I actually didn't know some editors let you do that. (Also got to figure out how to configure iterm2 to let me do it with vim :D)

This will be available in version 1.1.0.
